config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index] do
    member do
      resources :secrets, only: [:new]
      resources :friendships, only: [:create]
    end
  end
  resources :friendships, only: [:destroy]
  resources :secrets, only: [:create]
  resource :session, :only => [:create, :destroy, :new]

  delete "users/:id/friendships", to: "friendships#destroy", as: "friendships"

  resources :tags, only: :index

  root :to => "users#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :out_friend_id, :in_friend_id

  belongs_to :out_friend,
  class_name: "User",
  foreign_key: :out_friend_id

  belongs_to :in_friend,
  class_name: "User",
  foreign_key: :in_friend_id

  def self.can_friend?(out_friend_id, in_friend_id)
    (out_friend_id != in_friend_id) && !exists?(out_friend_id: out_friend_id, in_friend_id: in_friend_id) && !exists?(out_friend_id: in_friend_id, in_friend_id: out_friend_id)
  end

  def self.can_unfriend?(out_friend_id, in_friend_id)
    (out_friend_id != in_friend_id) && (exists?(out_friend_id: out_friend_id, in_friend_id: in_friend_id) || exists?(out_friend_id: in_friend_id, in_friend_id: out_friend_id))
  end
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :title, :tag_ids

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  has_many :secret_taggings
  has_many :tags, through: :secret_taggings, source: :tag

  validates :author_id, :recipient_id, :title, :presence => true
end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :secret_id, :tag_id

  belongs_to :secret
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :title

  has_many :secret_taggings
  has_many :secrets, through: :secret_taggings, source: :secret
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    sleep(2)
    Friendship.create!(out_friend_id: params[:id],
      in_friend_id: current_user.id )
      render nothing: true
  end

  def destroy
    sleep(2)
    @friendship = Friendship.find_by_out_friend_id_and_in_friend_id(params[:id], current_user.id)

    @friendship.destroy
    render nothing: true
  end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
  end

  def create
    secret = Secret.new(params[:secret])
    secret.author_id = current_user.id

    secret.save

    render json: secret
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    render json: @tags
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    @tags = Tag.all

    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<form class="secrets_form" action="<%= secrets_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" id="secret_recipient_id" name="secret[recipient_id]" value="<%= params[:id] %>">

  <div id="secret-tag-selects">
    <select name="secret[tag_ids][]" id="secret_tags" >
    </select>
  </div>

  <a id="one_more_tag" href="#">Add another tag</a>

  <label for="secret_title">Title</label>
  <input type="text" id="secret_title" name="secret[title]">

  <p><input type="submit" class="submit" value="Make Secret"></p>
</form>

app/views/secrets/new.html.erb
<form action="<%= secrets_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="secret[recipient_id]" value="<%= params[:id] %>">


  <label for="secret_title">Title</label>
  <input type="text" name="secret[title]" id="secret_title">

  <p><input type="submit" value="Make Secret"></p>
</form>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<div class="users">
<h1>Users</h1>
<% @users.each do |user| %>

  <h2><%= user.username %></h2>

  <div class="friend_buttons">
    <% friend_status =  Friendship.can_friend?(user.id, current_user.id) ? "friend can-friend" : "friend" %>
      <button class="<%= friend_status %>" data-friend-id="<%= user.id %>">Friend</button>

    <% unfriend_status =  Friendship.can_unfriend?(user.id, current_user.id) ? "unfriend can-unfriend" : "unfriend" %>
      <button class="<%= unfriend_status %>" data-friend-id="<%= user.id %>">Unfriend</button>
  </div>
<% end %>
</div>

<script>
$(document).ready( function() {
  $('.users').on("click", ".friend", function() {
    var $this = $(this);
    var friendId = $this.attr('data-friend-id');
    $this.attr("disabled", "disabled");
    $this.empty();
    $this.append('Friending...');
    $.ajax({
      url: "/users/" + friendId + "/friendships",
      type: "post",
      data: {},
      success: function () {
        $this.empty();
        $this.append("Friend");
        $this.removeAttr("disabled");
        $(".friend[data-friend-id=" + friendId + "]").toggleClass("can-friend");
        $(".unfriend[data-friend-id=" + friendId + "]").toggleClass("can-unfriend");
      }
    });
  });

  $('.users').on("click", ".unfriend", function() {
    var $this = $(this);
    var friendId = $this.attr('data-friend-id');
    $this.attr("disabled", "disabled");
    $this.empty();
    $this.append('Unfriending...');
    $.ajax({
      url: "/users/" + friendId + "/friendships/",
      type: "delete",
      data: {},
      success: function () {
        $this.empty();
        $this.append("Unfriend");
        $this.removeAttr("disabled");
        $(".friend[data-friend-id=" + friendId + "]").toggleClass("can-friend");
        $(".unfriend[data-friend-id=" + friendId + "]").toggleClass("can-unfriend");
      }
    });
  });
})

</script>

<style>
.friend {
  display: none;
}

.unfriend {
  display: none;
}

.can-friend {
  display: inline;
}

.can-unfriend {
  display: inline;
}

</style>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Secrets</h2>
<ul class="secrets">
  <% @user.received_secrets.each do |secret| %>
    <li><%= secret.title %></li>
  <% end %>
</ul>

<%= render 'secrets/form' %>

<script type="application/json" id="bootstrapped_tags_json">
 { "tags" : <%= @tags.to_json.html_safe %>}
</script>

<script type="text/template" id="tag_template">
<%% var tags = JSON.parse($("#bootstrapped_tags_json").html()); %>
<select>
<%% tags.tags.forEach(function (tag) { %>
  <option value="<%%= tag.id %>"><%%=tag.title %></option>
<%%  });%>
</select>
</script>

<script>

$(document).ready(function () {

  var tags = JSON.parse($("#bootstrapped_tags_json").html());
  tags.tags.forEach(function(tag) {
    $('#secret_tags').append("<option value=" + tag.id + ">" + tag.title + "</option>");
  })


  var addSecretTagSelect = function() {
    var tag_template = $('#tag_template').html();
    var compiled_template = _.template(tag_template);
    $('#secret-tag-selects').append(compiled_template);
  }


  $('#one_more_tag').on("click", function(event){
    event.preventDefault();
    addSecretTagSelect();
  })


  var recipient_id = $('#secret_recipient_id').attr('value')
  $('.secrets_form').on("submit", function(event) {
    event.preventDefault();
    var data = ($(event.target).serialize());
    var $this = $(this);

    $.ajax({
      url: "/secrets",
      type: "post",
      data: data ,
      success: function (resp) {
        console.log(resp);
        $('#secret_title').val("");
        $('.secrets').append("<li>" + resp.title +  "</li>");
      }
    });
  });

})

</script>